spring.application.name=devvault

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

spring.data.redis.host=localhost
spring.data.redis.port=6379
secret.encryption.key=${SECRET_ENCRYPTION_KEY}